#!/bin/bash

# Copyright (c) 2015 Tom De Vylder <tom_at_penumbra.be>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

if [ -f /etc/redhat-release ];
then
  if [ -n "$(which needs-restarting)" ];
  then
    services=$(needs-restarting | wc -l)
    case $services in
      [0]*)
        echo "OK - $services services need to be restarted"
        exit 0
        ;;

      *)
        echo "CRITICAL - $services services need to be restarted"
        exit 2
        ;;
    esac
  else
    echo "UNKNOWN - 'needs-restarting' binary not found. Make sure yum-utils is installed."
    exit 3
  fi

elif [ -f /etc/debian_version ];
then
  if [ -n "$(which checkrestart)" ];
  then
    services=$(checkrestart | grep -iE ^found | head -1 | sed -e 's/^Found\ //g' | sed -e 's/\ processes\ .*//g')
    case $services in
      [0]*)
        echo "OK - $services services need to be restarted"
        exit 0
        ;;

      *)
        echo "CRITICAL - $services services need to be restarted"
        exit 2
        ;;
    esac
  else
    echo $?
    echo "UNKNOWN - 'checkrestart' binary not found. Make sure debian-goodies is installed."
    exit 3
  fi

else
  echo "UNKNOWN - operatingsystem not supported"
fi
