#!/bin/bash
# Script to monitor BGP conections.
# MIT License Copyright (c) [2017] [Yornik Heyl] (yornik@yornik.nl)

# helper function by Dave Simons
die () {
  RETVAL=$1
  shift
  echo $@
  exit $RETVAL
}

status_string=$(vtysh -c 'show  ip bgp  neighbors'| awk '/Description: '$1'/,/BGP state/' | sed -n -e 's/^.*BGP state = //p' )

if [ -z "$status_string" ]; then
 die 3 "[UNKNOWN] BGP conection with $1 is not cofigured "
fi


if echo "$status_string" |grep --quiet Established ;then
 die 0 "[OK] BGP conection with $1 is up"
else
 die 2 "[ERROR] BGP conection with $1 is down in state $status_string"
fi
